mode: "sbs"
model_dir: "../AlphaMath-7B/" 
swap_space: 16
temperature: 0.6
max_depth: 10
prompt_wrap: "react_sft" 
result_unwrap: "react_sft"
step_delim: "\n"
stop: ["\n</code>", "</code>", "</step>"]
seed: 42
need_value_func: True
step_beam_width: 1      # B1
n_generate_sample: 5    # B2
best_of: 5
remove_duplicate: True
verbose: False
